name: dash
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.1=py38h50d1736_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hed1de0f_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.10.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38hed1de0f_1004
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.5.18.1=h033912b_0
  - cffi=1.15.0=py38h1a44b6c_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=37.0.1=py38hf6deb26_0
  - debugpy=1.6.0=py38h038c8f4_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py38h50d1736_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - ipykernel=6.13.0=py38h60dac5d_0
  - ipython=8.4.0=py38h50d1736_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=py38h50d1736_1
  - jinja2=3.1.2=pyhd8ed1ab_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.5.1=pyhd8ed1ab_0
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py38h50d1736_0
  - jupyter_server=1.17.0=pyhd8ed1ab_0
  - jupyterlab=3.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.14.0=pyhd8ed1ab_0
  - libcxx=14.0.4=hc203e6f_0
  - libffi=3.4.2=h0d85af4_5
  - libsodium=1.0.18=hbcb3906_1
  - libzlib=1.2.12=h6c3fc93_0
  - markupsafe=2.1.1=py38hed1de0f_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h96a0964_1005
  - nbclassic=0.3.7=pyhd8ed1ab_0
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - notebook=6.4.11=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - openssl=3.0.3=hfe4f2af_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.18=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.1.2=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psutil=5.9.1=py38h0dd4459_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38hed1de0f_1
  - pysocks=1.7.1=py38h50d1736_5
  - python=3.8.13=h66c20e1_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2022.1=pyhd8ed1ab_0
  - pyzmq=23.0.0=py38h34ba744_0
  - readline=8.1=h05e3726_0
  - requests=2.27.1=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.3.2=py38h50d1736_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py38h50d1736_3
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.38.5=hd9f0692_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - terminado=0.15.0=py38h50d1736_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.1=py38hed1de0f_3
  - traitlets=5.2.2.post1=pyhd8ed1ab_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h6c3fc93_0
  - pip:
    - ansi2html==1.7.0
    - brotli==1.0.9
    - certifi==2022.5.18.1
    - click==8.1.3
    - dash==2.4.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - flask==2.1.2
    - flask-compress==1.12
    - itsdangerous==2.1.2
    - jupyter-dash==0.4.2
    - numpy==1.22.4
    - pandas==1.4.2
    - plotly==5.8.0
    - retrying==1.3.3
    - tenacity==8.0.1
    - werkzeug==2.1.2
prefix: /Users/diego/opt/anaconda3/envs/dash
